/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.numberaddition;

import netcrackkur.*;
import java.util.*;
import java.io.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import netcrackkur.controllers.ServiceController;
import java.util.List;
import java.util.HashMap;

/**
 *
 * @author Elder
 */
public class ContactEditorUI extends javax.swing.JFrame {
private List<Track> trackList = new LinkedList<Track>();
private List<Genre> genreList = new LinkedList<Genre>();
ServiceController serviceController = ServiceController.getInstance();
    /**
     * Creates new form ContactEditorUI
     * 
     */
    public ContactEditorUI() throws IOException, DuplicateSubjectException, ClassNotFoundException {
        initComponents();
        jaddPanel.setVisible(false);
        
        DefaultTableModel myModel = (DefaultTableModel)jTable1.getModel();
        
        HashMap<String, String> nameOfFile = new HashMap<>();
        nameOfFile.put("0", "Cash.NetCrackKur");
        trackList = (List<Track>) serviceController.callController(ServiceController.OPERATION.LOAD, null, nameOfFile);
        for (Track track: trackList)
        {
            
        myModel.addRow(new Object[]{track.getGenre().getName(),track.getName(),track.getartist(), track.getAlbum(), track.getTime() });
        jTable1.setModel(myModel);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jaddPanel = new javax.swing.JPanel();
        jAddTime = new javax.swing.JTextField();
        jAddJanrNazv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAddNazv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jAddIspoln = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jAddAlbum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        fileSave = new javax.swing.JMenuItem();
        fileDownload = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        editAdding = new javax.swing.JMenuItem();
        editDelling = new javax.swing.JMenuItem();
        editView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jAddTime.setText("322");

        jAddJanrNazv.setText("Имя");

        jLabel4.setText("Длина трека");

        jLabel5.setText("Имя жанра");

        jAddNazv.setText("Имя");

        jLabel1.setText("Имя трэка");

        jAddIspoln.setText("Артист");
        jAddIspoln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddIspolnActionPerformed(evt);
            }
        });

        jLabel2.setText("Исполнитель");

        jAddAlbum.setText("Альбом");

        jLabel3.setText("Альбом");

        jButton1.setText("Создать запись");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jaddPanelLayout = new javax.swing.GroupLayout(jaddPanel);
        jaddPanel.setLayout(jaddPanelLayout);
        jaddPanelLayout.setHorizontalGroup(
            jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaddPanelLayout.createSequentialGroup()
                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jAddNazv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jAddIspoln, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jAddAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jAddJanrNazv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jaddPanelLayout.setVerticalGroup(
            jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaddPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAddAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAddJanrNazv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddIspoln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddNazv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(jButton1)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jaddPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Жанр", "Название", "Исполнитель", "Альбом", "Длительность"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton3.setText("Применить изменения");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuFile.add(menuNew);

        fileSave.setText("Save");
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveActionPerformed(evt);
            }
        });
        menuFile.add(fileSave);

        fileDownload.setText("Load");
        fileDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileDownloadActionPerformed(evt);
            }
        });
        menuFile.add(fileDownload);

        fileExit.setText("Exit");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        menuFile.add(fileExit);

        jMenu.add(menuFile);

        menuEdit.setText("Edit");

        editAdding.setText("Add");
        editAdding.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAddingActionPerformed(evt);
            }
        });
        menuEdit.add(editAdding);

        editDelling.setText("Delete");
        editDelling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editDellingActionPerformed(evt);
            }
        });
        menuEdit.add(editDelling);

        editView.setText("View");
        editView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editViewActionPerformed(evt);
            }
        });
        menuEdit.add(editView);

        jMenu.add(menuEdit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(40, 40, 40)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenu1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ComponentAdded

    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveActionPerformed
        FileDialog fdlg = new FileDialog(this, "Save file as...", FileDialog.SAVE);
        fdlg.setDirectory("C:\\");
        fdlg.setFile("*.NCrack");
        fdlg.setVisible(true);
        String filename = fdlg.getDirectory()+fdlg.getFile();
        if (fdlg.getFile() == null) {
            //System.out.println("You cancelled the choice"); не надо так)
        } else {
            try
            {
                
                try {
                    HashMap<String, String> nameOfFile = new HashMap<>();
                    nameOfFile.put("0", filename);
                    Object op = serviceController.callController(ServiceController.OPERATION.SAVE, trackList, nameOfFile);
                    int i = 0;
                } catch (DuplicateSubjectException | ClassNotFoundException ex) {
                    Logger.getLogger(ContactEditorUI.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            catch (IOException e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "IOException has been caught");
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_fileSaveActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
                try
            {
                    HashMap<String, String> nameOfFile = new HashMap<>();
                    nameOfFile.put("0", "Cash.NetCrackKur");
                    try {
                        serviceController.callController(ServiceController.OPERATION.SAVE, trackList, nameOfFile);
                    } catch (DuplicateSubjectException | ClassNotFoundException ex) {
                        Logger.getLogger(ContactEditorUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
                
            }
            catch (IOException e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "IOException has been caught");
            }
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        jaddPanel.setVisible(true);
        jPanel1.setVisible(false);
        trackList.clear();
        jTable1.removeAll();
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNewActionPerformed

    private void jAddartistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddartistActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jAddartistActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Track p = new Track( jAddNazv.getText(), jAddIspoln.getText(), jAddAlbum.getText(), Integer.parseInt(jAddTime.getText()),new Genre(jAddJanrNazv.getText()));
        trackList.add(0, p);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileDownloadActionPerformed
        // TODO add your handling code here:
        FileDialog fdlg = new FileDialog(this, "Save file as...", FileDialog.LOAD);
        fdlg.setDirectory("C:\\");
        fdlg.setFile("*.NCrack");
        fdlg.setVisible(true);
        String filename = fdlg.getDirectory()+fdlg.getFile();
        if (fdlg.getFile() == null) {
            //System.out.println("You cancelled the choice"); не надо так
        } else {
            try
            {
                    HashMap<String, String> nameOfFile = new HashMap<>();
                    nameOfFile.put("0", filename);
                    trackList = (List<Track>) serviceController.callController(ServiceController.OPERATION.LOAD, null, nameOfFile);
            }
            catch (IOException | DuplicateSubjectException | ClassNotFoundException e)
            {
                JOptionPane.showMessageDialog(new JFrame(), "IOException has been caught");
            }
        }
    }//GEN-LAST:event_fileDownloadActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    // TODO add your handling code here:
        IzmenenieTabl k = new IzmenenieTabl();
        trackList = k.getTrackList(jTable1.getModel());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
        try
            {
                
                    HashMap<String, String> nameOfFile = new HashMap<>();
                    nameOfFile.put("0", "Cash.NetCrackKur");
                    try {
                        serviceController.callController(ServiceController.OPERATION.SAVE, trackList, nameOfFile);
                    } catch (DuplicateSubjectException | ClassNotFoundException ex) {
                        Logger.getLogger(ContactEditorUI.class.getName()).log(Level.SEVERE, null, ex);
                    }
            
            }
            catch (IOException e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "IOException has been caught");
            }
                System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jAddIspolnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddIspolnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddIspolnActionPerformed

    private void editViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editViewActionPerformed
        // TODO add your handling code here:
        jaddPanel.setVisible(false);
        jPanel1.setVisible(true);
        jButton3.setVisible(true);
        DefaultTableModel myModel = (DefaultTableModel)jTable1.getModel();

        while (myModel.getRowCount()>0)
        {
            myModel.removeRow(myModel.getRowCount()-1);
        }

        for (Track track: trackList)
        myModel.addRow(new Object[]{track.getGenre().getName(),track.getName(),track.getartist(), track.getAlbum(), track.getTime() });
        jTable1.setModel(myModel);

    }//GEN-LAST:event_editViewActionPerformed

    private void editDellingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editDellingActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedColumn();
        if (index == -1) JOptionPane.showMessageDialog(new Frame(), "not selected track");
        else{
            try {
                trackList.remove(index);
                jTable1.removeRowSelectionInterval(index, index);
                editView.doClick();
                jTable1.clearSelection();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(new Frame(), "auch!");
                Logger.getLogger(ContactEditorUI.class.getName()).log(Level.SEVERE, null, e);
            }
        }
    }//GEN-LAST:event_editDellingActionPerformed

    private void editAddingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAddingActionPerformed
        // TODO add your handling code here:
        jaddPanel.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_editAddingActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editAdding;
    private javax.swing.JMenuItem editDelling;
    private javax.swing.JMenuItem editView;
    private javax.swing.JMenuItem fileDownload;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JTextField jAddAlbum;
    private javax.swing.JTextField jAddIspoln;
    private javax.swing.JTextField jAddJanrNazv;
    private javax.swing.JTextField jAddNazv;
    private javax.swing.JTextField jAddTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel jaddPanel;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuNew;
    // End of variables declaration//GEN-END:variables
}
