/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.numberaddition;

import netcrackkur.*;
import java.util.*;
import java.io.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
import javax.swing.JFrame;

/**
 *
 * @author Elder
 */
public class ContactEditorUI extends javax.swing.JFrame {
TrackList trList = new TrackList();
    /**
     * Creates new form ContactEditorUI
     */
    public ContactEditorUI() {
        initComponents();
        jaddPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jaddPanel = new javax.swing.JPanel();
        jAddTime = new javax.swing.JTextField();
        jAddJanrNazv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jAddNazv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jAddIspoln = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jAddAlbum = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenu = new javax.swing.JMenuBar();
        menuFile = new javax.swing.JMenu();
        menuNew = new javax.swing.JMenuItem();
        fileSave = new javax.swing.JMenuItem();
        fileDownload = new javax.swing.JMenuItem();
        fileExit = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenu();
        editAdding = new javax.swing.JMenuItem();
        editDelling = new javax.swing.JMenuItem();
        editEdit = new javax.swing.JMenuItem();
        editView = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jAddTime.setText("322");

        jAddJanrNazv.setText("Имя");

        jLabel4.setText("Длина трека");

        jLabel5.setText("Имя жанра");

        jAddNazv.setText("Имя");

        jLabel1.setText("Имя трэка");

        jAddIspoln.setText("Артист");
        jAddIspoln.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddIspolnActionPerformed(evt);
            }
        });

        jLabel2.setText("Исполнитель");

        jAddAlbum.setText("Альбом");

        jLabel3.setText("Альбом");

        jButton1.setText("Создать запись");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jaddPanelLayout = new javax.swing.GroupLayout(jaddPanel);
        jaddPanel.setLayout(jaddPanelLayout);
        jaddPanelLayout.setHorizontalGroup(
            jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaddPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jAddJanrNazv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jAddNazv, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jaddPanelLayout.createSequentialGroup()
                                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jAddIspoln, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jAddAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jaddPanelLayout.setVerticalGroup(
            jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jaddPanelLayout.createSequentialGroup()
                .addGroup(jaddPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddIspoln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jaddPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jAddNazv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jAddJanrNazv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        menuFile.setText("File");

        menuNew.setText("New");
        menuNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNewActionPerformed(evt);
            }
        });
        menuFile.add(menuNew);

        fileSave.setText("Save");
        fileSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileSaveActionPerformed(evt);
            }
        });
        menuFile.add(fileSave);

        fileDownload.setText("Download");
        fileDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileDownloadActionPerformed(evt);
            }
        });
        menuFile.add(fileDownload);

        fileExit.setText("Exit");
        fileExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileExitActionPerformed(evt);
            }
        });
        menuFile.add(fileExit);

        jMenu.add(menuFile);

        menuEdit.setText("Edit");

        editAdding.setText("Add");
        menuEdit.add(editAdding);

        editDelling.setText("Delete");
        menuEdit.add(editDelling);

        editEdit.setText("Edit");
        editEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editEditActionPerformed(evt);
            }
        });
        menuEdit.add(editEdit);

        editView.setText("View");
        editView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editViewActionPerformed(evt);
            }
        });
        menuEdit.add(editView);

        jMenu.add(menuEdit);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jaddPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenu1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ComponentAdded

    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileSaveActionPerformed
        FileDialog fdlg = new FileDialog(this, "Save file as...", FileDialog.SAVE);
        fdlg.setDirectory("C:\\");
        fdlg.setFile("*.NCrack");
        fdlg.setVisible(true);
        String filename = fdlg.getDirectory()+fdlg.getFile();
        if (filename == null) {
            System.out.println("You cancelled the choice");
        } else {
            try
            {
               trList.serializeIt(filename);
            }
            catch (IOException e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "IOException has been caught");
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_fileSaveActionPerformed

    private void fileExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_fileExitActionPerformed

    private void menuNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNewActionPerformed
        jaddPanel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNewActionPerformed

    private void jAddIspolnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddIspolnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jAddIspolnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Track p = new Track( jAddNazv.getText(), jAddIspoln.getText(), jAddAlbum.getText(), Integer.parseInt(jAddTime.getText()),new Janr(jAddJanrNazv.getText()));
        trList.addTrackN(0, p);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fileDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileDownloadActionPerformed
        // TODO add your handling code here:
        FileDialog fdlg = new FileDialog(this, "Save file as...", FileDialog.LOAD);
        fdlg.setDirectory("C:\\");
        fdlg.setFile("*.NCrack");
        fdlg.setVisible(true);
        String filename = fdlg.getDirectory()+fdlg.getFile();
        if (filename == null) {
            System.out.println("You cancelled the choice");
        } else {
            try
            {
               trList.deSerializeIt(filename);
            }
            catch (Exception e)
            {
                JFrame frame = new JFrame();
                JOptionPane.showMessageDialog(frame, "IOException has been caught");
            }
        }
    }//GEN-LAST:event_fileDownloadActionPerformed

    private void editEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editEditActionPerformed
        // TODO add your handling code here:

       Track tr = trList.getTrackN(0);
        jAddNazv.setText(tr.getName());
        jAddIspoln.setText(tr.getIspoln());
        jAddAlbum.setText(tr.getAlbum());
        jAddTime.setText(Integer.toString(tr.getTime()));
        jAddJanrNazv.setText(tr.getJanr().getName());
        
    }//GEN-LAST:event_editEditActionPerformed

    private void editViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editViewActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_editViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContactEditorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContactEditorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem editAdding;
    private javax.swing.JMenuItem editDelling;
    private javax.swing.JMenuItem editEdit;
    private javax.swing.JMenuItem editView;
    private javax.swing.JMenuItem fileDownload;
    private javax.swing.JMenuItem fileExit;
    private javax.swing.JMenuItem fileSave;
    private javax.swing.JTextField jAddAlbum;
    private javax.swing.JTextField jAddIspoln;
    private javax.swing.JTextField jAddJanrNazv;
    private javax.swing.JTextField jAddNazv;
    private javax.swing.JTextField jAddTime;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JPanel jaddPanel;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JMenu menuFile;
    private javax.swing.JMenuItem menuNew;
    // End of variables declaration//GEN-END:variables
}
